name: ELT App - Lint Code and Run Unit Tests

on: [workflow_dispatch]  # also add: push, pull_request  - also:  on.<pull_request|pull_request_target>.<branches|branches-ignore>

jobs:
  test-app:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest 
          cd BIEnergyUsageApp
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          cd BIEnergyUsageApp
          flake8 . --count --show-source --statistics --max-line-length=120

      - name: Test with pytest
        if: always()
        run: |
          cd BIEnergyUsageApp
          pytest
